AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: save-data

Globals:
  Function:
    Timeout: 15
    MemorySize: 520

Resources:
  MySaveSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "MySaveSQS.fifo"
      FifoQueue: true

  Subscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      TopicArn: arn:aws:sns:us-east-1:381492193067:nfe-data-parsed.fifo
      Endpoint: !GetAtt MySaveSQS.Arn
      Protocol: sqs
      RawMessageDelivery: true

  MySaveSQSQueuePolicy:
    Type: "AWS::SQS::QueuePolicy"
    Properties:
      Queues:
        - !Ref MySaveSQS
      PolicyDocument:
        Statement:
          - Effect: "Allow"
            Principal: "*"
            Action:
              - sqs:SendMessage
            Resource:
              - !GetAtt MySaveSQS.Arn
            Condition:
              ArnEquals:
                "aws:SourceArn": arn:aws:sns:us-east-1:381492193067:nfe-data-parsed.fifo

  MySaveFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: scrapper/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        SqsEvento:
          Type: SQS
          Properties:
            Queue: !GetAtt MySaveSQS.Arn
      Policies:
        - Statement:
            - Effect: "Allow"
              Action:
                - "sqs:ReceiveMessage"
                - "sqs:DeleteMessage"
                - "sqs:GetQueueAttributes"
              Resource: "*"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
